const baseURL = 'http://www.ilyasgaripov.ru/projects/';

export const projects = [
  {
    id: 1,
    page: 1,
    title: 'Online Shop',
    description: `Web application, allows add an items into cart and make an order`,
    demoURL: baseURL + 'online-shop/',
    sourceURL: 'https://github.com/ilyasgaripov97/online-shop',
    badges: ['html', 'css', 'javascript', 'react', 'redux'],
  },
  {
    id: 2,
    page: 1,
    title: 'Currency Converter',
    description: `Web application to convert from one currency to another`,
    demoURL: baseURL + 'currency-converter/',
    sourceURL: 'https://github.com/ilyasgaripov97/currency-converter',
    badges: ['html', 'css', 'javascript', 'react'],
  },
  {
    id: 3,
    page: 1,
    title: 'Etch A Sketch',
    description: `Drawing web application, which has three different drawing modes: rgb, darken and default. The "rgb" mode,
color for each cell picked randomly. The "darken" mode represent scales of black and black color used as"default`,
    demoURL: baseURL + 'etch-a-sketch/',
    sourceURL: 'https://github.com/ilyasgaripov97/etch-a-sketch',
    badges: ['html', 'css', 'javascript'],
  },
  {
    id: 4,
    page: 1,
    title: 'Feed',
    description: `Infinite feed of posts`,
    demoURL: baseURL + 'feed/',
    sourceURL: 'https://github.com/ilyasgaripov97/feed',
    badges: ['html', 'css', 'javascript'],
  },
  {
    id: 5,
    page: 2,
    title: 'Tic Tac Toe',
    description: `Tic Tac Toe game, four by four grid`,
    demoURL: baseURL + 'etch-a-sketch/',
    sourceURL: 'https://github.com/ilyasgaripov97/tic-tac-toe',
    badges: ['html', 'css', 'javascript'],
  },
];